In [1]:
import numpy as np

In [6]:
arr0=np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
arr1 = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])

stack=np.hstack((arr0,arr1))
print(stack)

[[ 1  2  3  4  5  6  7  8  9  1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99 11 22 33 44 55 66 77 88 99]]


In [60]:
arr=np.arange(1,25)
arr.resize(3,6)
print(arr)
print(np.split(arr,(3,8),axis=0))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]


###spilt array

In [30]:
arr1=np.hsplit(arr,(5,5))
print(arr1)

[array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]]), array([], shape=(3, 0), dtype=int64), array([[ 6],
       [12],
       [18]])]


In [39]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=np.sum(arr,axis=1)
print(arr1)
arr0=arr*2
print(arr0)



[10 26]
[[ 2  4  6  8]
 [10 12 14 16]]


In [40]:
print(arr[1])

[5 6 7 8]


In [110]:
a=np.array([[1,2],[3,4],[6,7]])
# s=a+np.ones((2,2))
# print(s)
print(np.max(a,axis=0))
print(a.ravel())
x=np.empty((4,3))
print("Empty:\n",x)
print("ones:\n",np.ones_like(a))
print("Full:\n",np.full_like(a,7))
print(np.random.rand(3))
print(np.random.randn(2))
print(np.random.random(3))
print(np.random.randint(1, 500, size=(100)))
r=np.random.default_rng()
print(r.random(3))

[6 7]
[1 2 3 4 6 7]
Empty:
 [[1.09998426e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.11529822e+277 1.34728689e+165]
 [3.89038433e-033 7.69860007e+169 5.75414243e-066]
 [1.16256713e+165 6.18607248e+169 6.60039064e-042]]
ones:
 [[1 1]
 [1 1]
 [1 1]]
Full:
 [[7 7]
 [7 7]
 [7 7]]
[0.24387206 0.66449982 0.65870374]
[-0.2241523  -0.24668922]
[0.81377186 0.40743998 0.44379369]
[476 207 215  98   5 252 208 468 121 276 333 336 313 268 373  44  87 336
  30 475 232 414 131 457 273 146 157 187 415 175 313 154 134 404 163  83
 439 394  80  11 204 210 282 346  70 482 125 276 336  84 271 130 376 441
 172 403 404 372 394 496 193 185 378 120 406 334 297  51 447 311 122  90
  85  27 236 485 322 296 318 285  29 289 251 252 380 460 307  95 281 112
 278 115 341  63 324 431 417 174  11 376]
[0.97245078 0.93794216 0.2026382 ]


###Unique
import rn

In [117]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, indices_list, occurrence_count,Inverse = np.unique(a, return_index=True,return_counts=True,return_inverse=True)
print(f"{unique_values}:{indices_list}")
print( occurrence_count,Inverse)

[11 12 13 14 15 16 17 18 19 20]:[ 0  2  3  4  5  6  7 12 13 14]
[0 0 1 2 3 4 5 6 1 2 0 3 7 8 9] [3 2 2 2 1 1 1 1 1 1]


In [122]:
a_2D=np.array([[1,2,3,4],[4,5,7,8],[9,10,11,12],[3,4,6,9]])
unique_values=np.unique(a_2D,axis=0)
print(unique_values)

[[ 1  2  3  4]
 [ 3  4  6  9]
 [ 4  5  7  8]
 [ 9 10 11 12]]


### Inverse an array 

In [131]:
ar_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar_3D=np.array([[[1,2],[3,4],[8,9]],[[5,6],[7,8],[2,3]]])

In_2D=np.flip(ar_2D,axis=0)
print(In_2D)

In_3D=np.flip(ar_3D,axis=0)
print(In_3D)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[[5 6]
  [7 8]
  [2 3]]

 [[1 2]
  [3 4]
  [8 9]]]


In [138]:
help(max)
help(np.unique)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.

Help on _ArrayFunctionDispatcher in module numpy:

unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
    *,
    equal_nan=True,
    sorted=True
)
    Find the unique elements of an array.

    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:

    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array

    Paramet

###how to save and load numpy objects

In [152]:
arr=np.array([1,2,3,4,5,6,7,8,9])
s=np.save('filename.npy', arr)
l=np.load('filename.npy')
print(l)

csv=np.savetxt('CSV.csv',arr)
lcsv=np.loadtxt('CSV.csv')
print(lcsv)

npz=np.savez('NPZ.npz',arr)
lnpz=np.load('NPZ.npz')
print(lnpz)
lnpz
arr

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
NpzFile 'NPZ.npz' with keys: arr_0


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reduce function 

In [163]:
arr = np.array([1, 2, 3, 4, 5])
arr1=np.array([3,4,7,8,9])
total_sum = np.add.reduce(arr)
Max=np.maximum.reduce(arr)
Multiply=arr*arr1
print(total_sum)
print('Maximum:',Max)
print('multiply:',Multiply)
print(np.sum(arr))
print(np.prod(arr))

15
Maximum: 5
multiply: [ 3  8 21 32 45]
15
120
